# Site settings
title: Achraf Belarif
email: acbe1325@aol.com
url: https://www.achrafbelarif.com
description: "Software Engineer Student "
repository: spydersy/spydersy.github.io

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#091109'
  links: '#d8ecd7'

# Footer settings
footer: Your Website

# "UA-NNNNNNNN-N"
# google_analytics: UA-131311056-1

# resume pdf public link in google drive
google-drive-resume-file-id: 14tgGi85z1oxJJBBvLNhCNJV4oSzAvNc2

# Social networks usernames
social:
  - title: github
    url: https://github.com/spydersy
  - title: twitter
    url: https://twitter.com/spydersy_
  - title: linkedin
    url: https://www.linkedin.com/in/achrafbelarif/

projects:
  - title: "Project 00"
    venue-publication: description 00
    url: https://google.com
  - title: "Project 01"
    venue-publication: description 01
    url: https://google.com
  - title: "Project 02"
    venue-publication: description 02
    url: https://google.com

# Build settings
markdown: kramdown
permalink: pretty
